global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@monitoring.com'

route:
  receiver: 'default-receiver'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  group_by: [alertname]
  routes:
  - receiver: 'slack'
    group_wait: 10s
    match_re:
      service: activemq

receivers:
  - name: 'default-receiver'
    email_configs:
    - to: 'trevisan@gmail.com'

  - name: 'slack'
    slack_configs:
    - send_resolved: true
      text: "{{ .CommonAnnotations.description }}"
      username: 'Prometheus'
      channel: '#prometheus'
      api_url: 'https://hooks.slack.com/services/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'

  - name: 'prometheus-msteams'
    webhook_configs: # https://prometheus.io/docs/alerting/configuration/#webhook_config 
    - send_resolved: true
      url: 'http://prometheus-msteams:2000/alertmanager' # the prometheus-msteams proxy
