route:
  group_by: ['alertname']
  group_interval: 30s
  repeat_interval: 30s
  group_wait: 30s
  routes:
    - match_re:
        severity: "warning"
        receiver: 'slack'
    - match_re:
          severity: "critical"
          receiver: 'prometheus-msteams'
    - receiver: 'slack'
receivers:
  - name: 'slack'
    slack_configs:
        - send_resolved: true
          text: "{{ .CommonAnnotations.description }}"
          username: 'Prometheus'
          channel: '#prometheus'
          api_url: 'https://hooks.slack.com/services/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'

  - name: 'prometheus-msteams'
    webhook_configs: # https://prometheus.io/docs/alerting/configuration/#webhook_config 
    - send_resolved: true
      url: 'http://prometheus-msteams:2000/alertmanager' # the prometheus-msteams proxy
