apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true

  - name: gdev-postgres
    type: postgres
    url: localhost:5432
    database: liberum
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: "disable"